### ISSUE TITLE
Packages are failing to resolve in core when referenced by module

### ISSUE THREAD

**Issue by stuartc** [OpenFn/adaptors#126]
I noticed some recently failing tests in [openfn/lightning](https://github.com/openfn/lightning).
When modules are referenced by their module name (i.e. `@openfn/language-http-latest` etc) `core` throws an exception.

After some debugging I found this:

```
54ca9 : {
54ca9 :   request: '@openfn/language-http-latest/package.json',
54ca9 :   options: undefined
54ca9 : }
54ca9 : Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/stuart/Sourcecode/lightning/priv/openfn/lib/node_modules/@openfn/language-http-latest/package.json
54ca9 :     at new NodeError (node:internal/errors:393:5)
54ca9 :     at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
54ca9 :     at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
54ca9 :     at resolveExports (node:internal/modules/cjs/loader:529:36)
54ca9 :     at Module._findPath (node:internal/modules/cjs/loader:569:31)
54ca9 :     at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
54ca9 :     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
54ca9 :     at safeResolve (/home/stuart/Sourcecode/lightning/priv/openfn/lib/node_modules/@openfn/core/lib/utils.js:29:20)
54ca9 :     at getModuleDetails (/home/stuart/Sourcecode/lightning/priv/openfn/lib/node_modules/@openfn/core/lib/utils.js:14:5)
54ca9 :     at Object.handler (/home/stuart/Sourcecode/lightning/priv/openfn/lib/node_modules/@openfn/core/lib/cli/execute-command.js:24:27) {
54ca9 :   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
54ca9 : }
54ca9 : 
```

This is a side effect of us moving to modules and the way that core looks up the adaptors `package.json`.

I have made a change to `core` here: https://github.com/OpenFn/core/pull/40 which saves us from cutting new releases for now. And all of this will be superceded with the new runtimes.

I would like to propose we add a conditional export to our `package.json` files:

```
...
  "exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    },
    "./package.json": "./package.json"
  },
```

**Comment by josephjclark** [comment]
Urgh, more complication!

Sure - I'll prepare a PR today with a conditional exports, which we'll release as part of the regular Friday schedule (as it doesn't sound urgent?)
