### ISSUE TITLE
`primero` A bug when using `getCases` on a new `@openfn/cli`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#189]
### Description 
A bug in primero adaptors when using 

### Logs

```
aleksakrolls@MacBook-Pro-5 tmp % openfn ./getPrimeroCases.js -ia primero@2.7.0 -s ./state.json
[CLI] ✔ Installing packages...
[CLI] ✔ Installation complete in 2ms
[CLI] ✔ Loaded state from ./state.json
[CLI] ✔ Compiled job from ./getPrimeroCases.js
Primero says: '200 OK'
/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/lib/Adaptor.js:317
          console.log(`${cases.length} cases retrieved from request: ${JSON.stringify(response.request, null, 2)}`);
                               ^
TypeError: Cannot read properties of undefined (reading 'length')
    at Request._callback (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/lib/Adaptor.js:317:32)
    at self.callback (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.12.1
```

###

**Comment by josephjclark** [comment]
This is also tracked in `kit` - not sure where the issue really belongs at this point https://github.com/OpenFn/kit/issues/146

I think a simple `getCases()` call is enough to trigger the issue.
